/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForFrontend
 * OpenAPI spec version: v1
 */

export type AIModelEnum = typeof AIModelEnum[keyof typeof AIModelEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AIModelEnum = {
  Gemini25Pro: 'Gemini25Pro',
  Gemini25Flash: 'Gemini25Flash',
  Gpt41Mini: 'Gpt41Mini',
  Gpt41: 'Gpt41',
  Gpt4o: 'Gpt4o',
  Gpt4oMini: 'Gpt4oMini',
  Gpt41Nano: 'Gpt41Nano',
} as const;
