/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForFrontend
 * OpenAPI spec version: v1
 */
import type { ContentSourceDto } from './contentSourceDto';

export interface ArticleDto {
  /** @nullable */
  id?: string | null;
  createdAt?: string;
  /** @nullable */
  title?: string | null;
  /** @minLength 1 */
  contentText: string;
  /** @nullable */
  imageUrl?: string | null;
  /** @nullable */
  sourceUrl?: string | null;
  source?: ContentSourceDto;
}
