/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForFrontend
 * OpenAPI spec version: v1
 */
import type { ChatMessageDto } from './chatMessageDto';

export interface ChatMessageDtoListPaginationResponse {
  totalCount?: number;
  /** @nullable */
  items?: ChatMessageDto[] | null;
}
