/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForFrontend
 * OpenAPI spec version: v1
 */

export type ContentStatusEnum = typeof ContentStatusEnum[keyof typeof ContentStatusEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ContentStatusEnum = {
  Draft: 'Draft',
  Published: 'Published',
  Deleted: 'Deleted',
} as const;
