/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForFrontend
 * OpenAPI spec version: v1
 */
import type { ContentStatusEnum } from './contentStatusEnum';
import type { ContentTypeEnum } from './contentTypeEnum';
import type { ProjectEnum } from './projectEnum';
import type { TagDto } from './tagDto';
import type { ArticleDto } from './articleDto';
import type { AuthorDto } from './authorDto';
import type { ContentSourceDto } from './contentSourceDto';

export interface ContentDto {
  /** @nullable */
  id?: string | null;
  createdAt?: string;
  readingDuration?: number;
  contentStatus?: ContentStatusEnum;
  contentType?: ContentTypeEnum;
  platformType?: ProjectEnum;
  publishedDate?: string;
  /** @nullable */
  tags?: TagDto[] | null;
  /** @nullable */
  articles?: ArticleDto[] | null;
  author?: AuthorDto;
  source?: ContentSourceDto;
  /** @nullable */
  featured?: boolean | null;
}
