/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForFrontend
 * OpenAPI spec version: v1
 */
import type { ContentTypeEnum } from './contentTypeEnum';

export type GetContentManagementApiGetFeaturedContentParams = {
contentType?: ContentTypeEnum;
};
