/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForFrontend
 * OpenAPI spec version: v1
 */
import type { LoginWithTwoFaResponse } from './loginWithTwoFaResponse';

export interface LoginWithTwoFaResponseApiResponse {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: LoginWithTwoFaResponse;
  /** @nullable */
  errors?: string[] | null;
  /** @nullable */
  errorCode?: string | null;
  statusCode?: number;
}
