/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForFrontend
 * OpenAPI spec version: v1
 */

export type ProjectEnum = typeof ProjectEnum[keyof typeof ProjectEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProjectEnum = {
  TrendAi: 'TrendAi',
  Algex: 'Algex',
} as const;
