/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForFrontend
 * OpenAPI spec version: v1
 */

export interface SendChatMessageRequest {
  /** @nullable */
  sessionId?: string | null;
  /** @nullable */
  userId?: string | null;
  /** @nullable */
  message?: string | null;
}
