/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForFrontend
 * OpenAPI spec version: v1
 */

export interface SignInWithSmsOtpRequest {
  /** @nullable */
  phoneNumber?: string | null;
  /** @nullable */
  code?: string | null;
  /** @nullable */
  verificationId?: string | null;
}
