/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForFrontend
 * OpenAPI spec version: v1
 */

export interface TagDto {
  id?: number;
  createdAt?: string;
  /** @nullable */
  name?: string | null;
}
