/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */

export interface AddPermissionToRoleRequest {
  projectId?: string;
  /** @nullable */
  roleName?: string | null;
  /** @nullable */
  permissionName?: string | null;
  /** @nullable */
  category?: string | null;
  /** @nullable */
  description?: string | null;
}
