/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */
import type { MethodBase } from './methodBase';
import type { AggregateExceptionData } from './aggregateExceptionData';
import type { Exception } from './exception';

export interface AggregateException {
  targetSite?: MethodBase;
  /** @nullable */
  readonly data?: AggregateExceptionData;
  innerException?: Exception;
  /** @nullable */
  helpLink?: string | null;
  /** @nullable */
  source?: string | null;
  hResult?: number;
  /** @nullable */
  readonly stackTrace?: string | null;
  /** @nullable */
  readonly innerExceptions?: readonly Exception[] | null;
  /** @nullable */
  readonly message?: string | null;
}
