/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */
import type { AllChatSessions } from './allChatSessions';

export interface AllChatSessionsListPaginationResponse {
  totalCount?: number;
  /** @nullable */
  items?: AllChatSessions[] | null;
}
