/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */
import type { AllChatSessionsListPaginationResponse } from './allChatSessionsListPaginationResponse';

export interface AllChatSessionsListPaginationResponseApiResponse {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: AllChatSessionsListPaginationResponse;
  /** @nullable */
  errors?: string[] | null;
  /** @nullable */
  errorCode?: string | null;
  statusCode?: number;
}
