/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */
import type { ChatMessageDto } from './chatMessageDto';
import type { UserProfileInfoDto } from './userProfileInfoDto';

export interface AllChatSessions {
  id?: string;
  createdAt?: string;
  userId?: string;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  messages?: ChatMessageDto[] | null;
  user?: UserProfileInfoDto;
  messageCount?: number;
}
