/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */
import type { TypeInfo } from './typeInfo';
import type { Type } from './type';
import type { MethodInfo } from './methodInfo';
import type { CustomAttributeData } from './customAttributeData';
import type { Module } from './module';
import type { SecurityRuleSet } from './securityRuleSet';

export interface Assembly {
  /** @nullable */
  readonly definedTypes?: readonly TypeInfo[] | null;
  /** @nullable */
  readonly exportedTypes?: readonly Type[] | null;
  /**
   * @deprecated
   * @nullable
   */
  readonly codeBase?: string | null;
  entryPoint?: MethodInfo;
  /** @nullable */
  readonly fullName?: string | null;
  /** @nullable */
  readonly imageRuntimeVersion?: string | null;
  readonly isDynamic?: boolean;
  /** @nullable */
  readonly location?: string | null;
  readonly reflectionOnly?: boolean;
  readonly isCollectible?: boolean;
  readonly isFullyTrusted?: boolean;
  /** @nullable */
  readonly customAttributes?: readonly CustomAttributeData[] | null;
  /**
   * @deprecated
   * @nullable
   */
  readonly escapedCodeBase?: string | null;
  manifestModule?: Module;
  /** @nullable */
  readonly modules?: readonly Module[] | null;
  /** @deprecated */
  readonly globalAssemblyCache?: boolean;
  readonly hostContext?: number;
  securityRuleSet?: SecurityRuleSet;
}
