/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */

export interface AssignRoleRequest {
  /** @nullable */
  userId?: string | null;
  /** @nullable */
  roleName: string | null;
}
