/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */

export type CallingConventions = typeof CallingConventions[keyof typeof CallingConventions];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CallingConventions = {
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
  NUMBER_32: 32,
  NUMBER_64: 64,
} as const;
