/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */

export interface ChangePasswordRequest {
  /** @nullable */
  userId?: string | null;
  /** @nullable */
  currentPassword: string | null;
  /** @nullable */
  newPassword: string | null;
}
