/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */
import type { ChatMessageDto } from './chatMessageDto';

export interface ChatSessionDto {
  id?: string;
  createdAt?: string;
  userId?: string;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  messages?: ChatMessageDto[] | null;
}
