/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */
import type { AIModelEnum } from './aIModelEnum';

export interface ChatSettingsDto {
  id?: string;
  createdAt?: string;
  aiModel: AIModelEnum;
  /** @nullable */
  aiRole: string | null;
}
