/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */
import type { ChatSessionDto } from './chatSessionDto';

export interface ChatSessionDtoApiResponse {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: ChatSessionDto;
  /** @nullable */
  errors?: string[] | null;
  /** @nullable */
  errorCode?: string | null;
  statusCode?: number;
}
