/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */
import type { SenderTypeEnum } from './senderTypeEnum';
import type { AIModelEnum } from './aIModelEnum';

export interface ChatMessageDto {
  id?: string;
  createdAt?: string;
  userId?: string;
  /** @nullable */
  aiRole?: string | null;
  /** @nullable */
  content?: string | null;
  senderType: SenderTypeEnum;
  /** @nullable */
  referencedMessageId?: string | null;
  isProcessed?: boolean;
  retryCount?: number;
  chatSessionId?: string;
  aiResponseTimeMs?: number;
  aiModel: AIModelEnum;
}
