/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */
import type { ChatSettingsDto } from './chatSettingsDto';

export interface ChatSettingsDtoApiResponse {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: ChatSettingsDto;
  /** @nullable */
  errors?: string[] | null;
  /** @nullable */
  errorCode?: string | null;
  statusCode?: number;
}
