/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */
import type { ClaimsIdentityBootstrapContext } from './claimsIdentityBootstrapContext';
import type { Claim } from './claim';

export interface ClaimsIdentity {
  /** @nullable */
  readonly authenticationType?: string | null;
  readonly isAuthenticated?: boolean;
  actor?: ClaimsIdentity;
  /** @nullable */
  bootstrapContext?: ClaimsIdentityBootstrapContext;
  /** @nullable */
  readonly claims?: readonly Claim[] | null;
  /** @nullable */
  label?: string | null;
  /** @nullable */
  readonly name?: string | null;
  /** @nullable */
  readonly nameClaimType?: string | null;
  /** @nullable */
  readonly roleClaimType?: string | null;
}
