/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */
import type { ClaimProperties } from './claimProperties';
import type { ClaimsIdentity } from './claimsIdentity';

export interface Claim {
  /** @nullable */
  readonly issuer?: string | null;
  /** @nullable */
  readonly originalIssuer?: string | null;
  /** @nullable */
  readonly properties?: ClaimProperties;
  subject?: ClaimsIdentity;
  /** @nullable */
  readonly type?: string | null;
  /** @nullable */
  readonly value?: string | null;
  /** @nullable */
  readonly valueType?: string | null;
}
