/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */
import type { Type } from './type';
import type { Module } from './module';
import type { CustomAttributeData } from './customAttributeData';
import type { MethodAttributes } from './methodAttributes';
import type { MethodImplAttributes } from './methodImplAttributes';
import type { CallingConventions } from './callingConventions';
import type { RuntimeMethodHandle } from './runtimeMethodHandle';
import type { MemberTypes } from './memberTypes';

export interface ConstructorInfo {
  /** @nullable */
  readonly name?: string | null;
  declaringType?: Type;
  reflectedType?: Type;
  module?: Module;
  /** @nullable */
  readonly customAttributes?: readonly CustomAttributeData[] | null;
  readonly isCollectible?: boolean;
  readonly metadataToken?: number;
  attributes?: MethodAttributes;
  methodImplementationFlags?: MethodImplAttributes;
  callingConvention?: CallingConventions;
  readonly isAbstract?: boolean;
  readonly isConstructor?: boolean;
  readonly isFinal?: boolean;
  readonly isHideBySig?: boolean;
  readonly isSpecialName?: boolean;
  readonly isStatic?: boolean;
  readonly isVirtual?: boolean;
  readonly isAssembly?: boolean;
  readonly isFamily?: boolean;
  readonly isFamilyAndAssembly?: boolean;
  readonly isFamilyOrAssembly?: boolean;
  readonly isPrivate?: boolean;
  readonly isPublic?: boolean;
  readonly isConstructedGenericMethod?: boolean;
  readonly isGenericMethod?: boolean;
  readonly isGenericMethodDefinition?: boolean;
  readonly containsGenericParameters?: boolean;
  methodHandle?: RuntimeMethodHandle;
  readonly isSecurityCritical?: boolean;
  readonly isSecuritySafeCritical?: boolean;
  readonly isSecurityTransparent?: boolean;
  memberType?: MemberTypes;
}
