/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */

export type ContentStatusEnum = typeof ContentStatusEnum[keyof typeof ContentStatusEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ContentStatusEnum = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
} as const;
