/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */

export type ContentTypeEnum = typeof ContentTypeEnum[keyof typeof ContentTypeEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ContentTypeEnum = {
  NUMBER_0: 0,
} as const;
