/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */

export interface CreateAuthorRequest {
  /** @nullable */
  fullName?: string | null;
  /** @nullable */
  imageUrl?: string | null;
  /** @nullable */
  title?: string | null;
}
