/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */
import type { JobInstanceModel } from './jobInstanceModel';

export interface CreateJobRequest {
  /** @nullable */
  method: string | null;
  /** @nullable */
  url: string | null;
  /** @nullable */
  jobInstances?: JobInstanceModel[] | null;
  enable: boolean;
}
