/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */

export interface CreateContentSourceRequest {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  logo?: string | null;
}
