/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */
import type { PlatformTypeEnum } from './platformTypeEnum';
import type { MessageChannelEnum } from './messageChannelEnum';

export interface CreateMessageTemplateRequest {
  platformType?: PlatformTypeEnum;
  /** @nullable */
  name: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  body?: string | null;
  channel?: MessageChannelEnum;
  /** @nullable */
  subject?: string | null;
}
