/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */
import type { PermissionDto } from './permissionDto';

export interface CreateRoleWithPermissionsRequest {
  projectId?: string;
  /** @nullable */
  roleName: string | null;
  /** @nullable */
  permissions: PermissionDto[] | null;
}
