/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */
import type { Type } from './type';
import type { CustomAttributeTypedArgumentValue } from './customAttributeTypedArgumentValue';

export interface CustomAttributeTypedArgument {
  argumentType?: Type;
  /** @nullable */
  value?: CustomAttributeTypedArgumentValue;
}
