/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */
import type { MemberInfo } from './memberInfo';
import type { CustomAttributeTypedArgument } from './customAttributeTypedArgument';

export interface CustomAttributeNamedArgument {
  memberInfo?: MemberInfo;
  typedValue?: CustomAttributeTypedArgument;
  /** @nullable */
  readonly memberName?: string | null;
  readonly isField?: boolean;
}
