/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */
import type { PlatformTypeEnum } from './platformTypeEnum';

export interface EmailSettingsDto {
  id?: string;
  createdAt?: string;
  platformType?: PlatformTypeEnum;
  /** @nullable */
  smtpHost?: string | null;
  smtpPort?: number;
  useSsl?: boolean;
  /** @nullable */
  senderEmail?: string | null;
  /** @nullable */
  senderName?: string | null;
  /** @nullable */
  username?: string | null;
  /** @nullable */
  password?: string | null;
}
