/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */
import type { PlatformTypeEnum } from './platformTypeEnum';
import type { EventTypeEnum } from './eventTypeEnum';
import type { EmailMessageEventParameters } from './emailMessageEventParameters';

export interface EmailMessageEvent {
  platformType?: PlatformTypeEnum;
  eventType?: EventTypeEnum;
  /** @nullable */
  to?: string | null;
  /** @nullable */
  body?: string | null;
  /** @nullable */
  subject?: string | null;
  /** @nullable */
  templateName?: string | null;
  useTemplate?: boolean;
  isHtml?: boolean;
  /** @nullable */
  parameters?: EmailMessageEventParameters;
}
