/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */

export type EventAttributes = typeof EventAttributes[keyof typeof EventAttributes];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EventAttributes = {
  NUMBER_0: 0,
  NUMBER_512: 512,
  NUMBER_1024: 1024,
} as const;
