/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */
import type { Type } from './type';
import type { Module } from './module';
import type { CustomAttributeData } from './customAttributeData';
import type { MemberTypes } from './memberTypes';
import type { EventAttributes } from './eventAttributes';
import type { MethodInfo } from './methodInfo';

export interface EventInfo {
  /** @nullable */
  readonly name?: string | null;
  declaringType?: Type;
  reflectedType?: Type;
  module?: Module;
  /** @nullable */
  readonly customAttributes?: readonly CustomAttributeData[] | null;
  readonly isCollectible?: boolean;
  readonly metadataToken?: number;
  memberType?: MemberTypes;
  attributes?: EventAttributes;
  readonly isSpecialName?: boolean;
  addMethod?: MethodInfo;
  removeMethod?: MethodInfo;
  raiseMethod?: MethodInfo;
  readonly isMulticast?: boolean;
  eventHandlerType?: Type;
}
