/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */
import type { MethodBase } from './methodBase';
import type { ExceptionData } from './exceptionData';

export interface Exception {
  targetSite?: MethodBase;
  /** @nullable */
  readonly message?: string | null;
  /** @nullable */
  readonly data?: ExceptionData;
  innerException?: Exception;
  /** @nullable */
  helpLink?: string | null;
  /** @nullable */
  source?: string | null;
  hResult?: number;
  /** @nullable */
  readonly stackTrace?: string | null;
}
