/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */
import type { Type } from './type';
import type { Module } from './module';
import type { CustomAttributeData } from './customAttributeData';
import type { MemberTypes } from './memberTypes';
import type { FieldAttributes } from './fieldAttributes';
import type { RuntimeFieldHandle } from './runtimeFieldHandle';

export interface FieldInfo {
  /** @nullable */
  readonly name?: string | null;
  declaringType?: Type;
  reflectedType?: Type;
  module?: Module;
  /** @nullable */
  readonly customAttributes?: readonly CustomAttributeData[] | null;
  readonly isCollectible?: boolean;
  readonly metadataToken?: number;
  memberType?: MemberTypes;
  attributes?: FieldAttributes;
  fieldType?: Type;
  readonly isInitOnly?: boolean;
  readonly isLiteral?: boolean;
  /** @deprecated */
  readonly isNotSerialized?: boolean;
  readonly isPinvokeImpl?: boolean;
  readonly isSpecialName?: boolean;
  readonly isStatic?: boolean;
  readonly isAssembly?: boolean;
  readonly isFamily?: boolean;
  readonly isFamilyAndAssembly?: boolean;
  readonly isFamilyOrAssembly?: boolean;
  readonly isPrivate?: boolean;
  readonly isPublic?: boolean;
  readonly isSecurityCritical?: boolean;
  readonly isSecuritySafeCritical?: boolean;
  readonly isSecurityTransparent?: boolean;
  fieldHandle?: RuntimeFieldHandle;
}
