/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */

export type GenericParameterAttributes = typeof GenericParameterAttributes[keyof typeof GenericParameterAttributes];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GenericParameterAttributes = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
  NUMBER_4: 4,
  NUMBER_8: 8,
  NUMBER_16: 16,
  NUMBER_28: 28,
  NUMBER_32: 32,
} as const;
