/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */

export type GetNotificationApiVerifyOtpParams = {
verificationId?: string;
code?: string;
phoneNumber?: string;
};
