/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */

export type GetUserApiGetAuthenticatorSetupParams = {
userId?: string;
email?: string;
appName?: string;
};
