/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */
import type { JobInstance } from './jobInstance';
import type { JobLog } from './jobLog';

export interface Job {
  id?: string;
  createdAt?: string;
  /** @nullable */
  updatedAt?: string | null;
  /** @nullable */
  method: string | null;
  /** @nullable */
  url: string | null;
  /** @nullable */
  jobInstances?: JobInstance[] | null;
  /** @nullable */
  jobLogs?: JobLog[] | null;
  enable: boolean;
}
