/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */
import type { JobInstanceModelHeaders } from './jobInstanceModelHeaders';
import type { JobInstanceModelQueryParams } from './jobInstanceModelQueryParams';
import type { JobInstanceModelRequestBody } from './jobInstanceModelRequestBody';

export interface JobInstanceModel {
  /** @nullable */
  cronExpression: string | null;
  enable: boolean;
  /** @nullable */
  headers?: JobInstanceModelHeaders;
  /** @nullable */
  queryParams?: JobInstanceModelQueryParams;
  /** @nullable */
  requestBody?: JobInstanceModelRequestBody;
}
