/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */
import type { Job } from './job';
import type { JobInstanceHeaders } from './jobInstanceHeaders';
import type { JobInstanceQueryParams } from './jobInstanceQueryParams';
import type { JobInstanceRequestBody } from './jobInstanceRequestBody';

export interface JobInstance {
  id?: string;
  createdAt?: string;
  /** @nullable */
  updatedAt?: string | null;
  jobId?: string;
  job?: Job;
  /** @nullable */
  cronExpression: string | null;
  /** @nullable */
  jobKey: string | null;
  enable: boolean;
  /** @nullable */
  headers?: JobInstanceHeaders;
  /** @nullable */
  queryParams?: JobInstanceQueryParams;
  /** @nullable */
  requestBody?: JobInstanceRequestBody;
}
