/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */
import type { JobInstanceDtoHeaders } from './jobInstanceDtoHeaders';
import type { JobInstanceDtoQueryParams } from './jobInstanceDtoQueryParams';
import type { JobInstanceDtoRequestBody } from './jobInstanceDtoRequestBody';

export interface JobInstanceDto {
  id?: string;
  createdAt?: string;
  /** @nullable */
  cronExpression: string | null;
  /** @nullable */
  jobKey: string | null;
  enable: boolean;
  /** @nullable */
  headers?: JobInstanceDtoHeaders;
  /** @nullable */
  queryParams?: JobInstanceDtoQueryParams;
  /** @nullable */
  requestBody?: JobInstanceDtoRequestBody;
}
