/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */

export interface JobLogDto {
  id?: string;
  createdAt?: string;
  /** @nullable */
  jobKey: string | null;
  startDate?: string;
  endDate?: string;
  success?: boolean;
  /** @nullable */
  failureMessage?: string | null;
  /** @nullable */
  updatedAt?: string | null;
  jobId?: string;
}
