/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */
import type { Job } from './job';

export interface JobLog {
  id?: string;
  createdAt?: string;
  /** @nullable */
  jobKey: string | null;
  startDate?: string;
  endDate?: string;
  success?: boolean;
  /** @nullable */
  failureMessage?: string | null;
  jobId?: string;
  job?: Job;
  /** @nullable */
  updatedAt?: string | null;
}
