/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */

export type LayoutKind = typeof LayoutKind[keyof typeof LayoutKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LayoutKind = {
  NUMBER_0: 0,
  NUMBER_2: 2,
  NUMBER_3: 3,
} as const;
