/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */
import type { LoginResponse } from './loginResponse';

export interface LoginResponseApiResponse {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: LoginResponse;
  /** @nullable */
  errors?: string[] | null;
  /** @nullable */
  errorCode?: string | null;
  statusCode?: number;
}
