/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */

export interface LoginResponse {
  requiresTwoFactor?: boolean;
  /** @nullable */
  temporaryToken?: string | null;
  /** @nullable */
  accessToken?: string | null;
  /** @nullable */
  refreshToken?: string | null;
  /** @nullable */
  phoneNumber?: string | null;
  /** @nullable */
  jwtExpireDate?: string | null;
  /** @nullable */
  refreshTokenExpireDate?: string | null;
  /** @nullable */
  twoFaProviders?: string[] | null;
}
