/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */
import type { TwoFactorMethodEnum } from './twoFactorMethodEnum';

export interface LoginWithTwoFaRequest {
  /** @nullable */
  code: string | null;
  /** @nullable */
  temporaryToken: string | null;
  method?: TwoFactorMethodEnum;
}
