/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */

export interface LoginWithTwoFaResponse {
  /** @nullable */
  accessToken?: string | null;
  /** @nullable */
  refreshToken?: string | null;
  /** @nullable */
  jwtExpireDate?: string | null;
  /** @nullable */
  refreshTokenExpireDate?: string | null;
}
