/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */

export interface LoginRequest {
  /** @nullable */
  email: string | null;
  /** @nullable */
  password: string | null;
  /** @nullable */
  twoFactorCode?: string | null;
  /** @nullable */
  twoFactorRecoveryCode?: string | null;
}
