/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */
import type { MemberTypes } from './memberTypes';
import type { Type } from './type';
import type { Module } from './module';
import type { CustomAttributeData } from './customAttributeData';

export interface MemberInfo {
  memberType?: MemberTypes;
  /** @nullable */
  readonly name?: string | null;
  declaringType?: Type;
  reflectedType?: Type;
  module?: Module;
  /** @nullable */
  readonly customAttributes?: readonly CustomAttributeData[] | null;
  readonly isCollectible?: boolean;
  readonly metadataToken?: number;
}
