/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */
import type { Assembly } from './assembly';
import type { ModuleHandle } from './moduleHandle';
import type { CustomAttributeData } from './customAttributeData';

export interface Module {
  assembly?: Assembly;
  /** @nullable */
  readonly fullyQualifiedName?: string | null;
  /** @nullable */
  readonly name?: string | null;
  readonly mdStreamVersion?: number;
  readonly moduleVersionId?: string;
  /** @nullable */
  readonly scopeName?: string | null;
  moduleHandle?: ModuleHandle;
  /** @nullable */
  readonly customAttributes?: readonly CustomAttributeData[] | null;
  readonly metadataToken?: number;
}
