/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */
import type { NotificationRecordDto } from './notificationRecordDto';

export interface NotificationRecordDtoListPaginationResponse {
  totalCount?: number;
  /** @nullable */
  items?: NotificationRecordDto[] | null;
}
