/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */
import type { NotificationRecordDtoListPaginationResponse } from './notificationRecordDtoListPaginationResponse';

export interface NotificationRecordDtoListPaginationResponseApiResponse {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: NotificationRecordDtoListPaginationResponse;
  /** @nullable */
  errors?: string[] | null;
  /** @nullable */
  errorCode?: string | null;
  statusCode?: number;
}
