/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */
import type { EventTypeEnum } from './eventTypeEnum';

export interface NotificationRecordDto {
  id?: string;
  createdAt?: string;
  eventType?: EventTypeEnum;
  /** @nullable */
  to?: string | null;
  /** @nullable */
  body?: string | null;
  /** @nullable */
  subject?: string | null;
  /** @nullable */
  templateName?: string | null;
  useTemplate?: boolean;
  isHtml?: boolean;
}
