/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */
import type { ParameterAttributes } from './parameterAttributes';
import type { MemberInfo } from './memberInfo';
import type { Type } from './type';
import type { ParameterInfoDefaultValue } from './parameterInfoDefaultValue';
import type { ParameterInfoRawDefaultValue } from './parameterInfoRawDefaultValue';
import type { CustomAttributeData } from './customAttributeData';

export interface ParameterInfo {
  attributes?: ParameterAttributes;
  member?: MemberInfo;
  /** @nullable */
  readonly name?: string | null;
  parameterType?: Type;
  readonly position?: number;
  readonly isIn?: boolean;
  readonly isLcid?: boolean;
  readonly isOptional?: boolean;
  readonly isOut?: boolean;
  readonly isRetval?: boolean;
  /** @nullable */
  readonly defaultValue?: ParameterInfoDefaultValue;
  /** @nullable */
  readonly rawDefaultValue?: ParameterInfoRawDefaultValue;
  readonly hasDefaultValue?: boolean;
  /** @nullable */
  readonly customAttributes?: readonly CustomAttributeData[] | null;
  readonly metadataToken?: number;
}
