/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */

export interface PermissionDto {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  category?: string | null;
  /** @nullable */
  description?: string | null;
}
