/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */

export type PropertyAttributes = typeof PropertyAttributes[keyof typeof PropertyAttributes];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PropertyAttributes = {
  NUMBER_0: 0,
  NUMBER_512: 512,
  NUMBER_1024: 1024,
  NUMBER_4096: 4096,
  NUMBER_8192: 8192,
  NUMBER_16384: 16384,
  NUMBER_32768: 32768,
  NUMBER_62464: 62464,
} as const;
