/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */
import type { Type } from './type';
import type { Module } from './module';
import type { CustomAttributeData } from './customAttributeData';
import type { MemberTypes } from './memberTypes';
import type { PropertyAttributes } from './propertyAttributes';
import type { MethodInfo } from './methodInfo';

export interface PropertyInfo {
  /** @nullable */
  readonly name?: string | null;
  declaringType?: Type;
  reflectedType?: Type;
  module?: Module;
  /** @nullable */
  readonly customAttributes?: readonly CustomAttributeData[] | null;
  readonly isCollectible?: boolean;
  readonly metadataToken?: number;
  memberType?: MemberTypes;
  propertyType?: Type;
  attributes?: PropertyAttributes;
  readonly isSpecialName?: boolean;
  readonly canRead?: boolean;
  readonly canWrite?: boolean;
  getMethod?: MethodInfo;
  setMethod?: MethodInfo;
}
