/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */

/**
 * @nullable
 */
export type RenderMessageTemplateRequestPlaceHolders = {[key: string]: string} | null;
