/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */
import type { PlatformTypeEnum } from './platformTypeEnum';
import type { RenderMessageTemplateRequestPlaceHolders } from './renderMessageTemplateRequestPlaceHolders';

export interface RenderMessageTemplateRequest {
  platformType?: PlatformTypeEnum;
  /** @nullable */
  templateName?: string | null;
  /** @nullable */
  placeHolders?: RenderMessageTemplateRequestPlaceHolders;
}
