/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */
import type { PermissionDto } from './permissionDto';

export interface RoleDto {
  id?: string;
  /** @nullable */
  name?: string | null;
  createdAt?: string;
  /** @nullable */
  updatedAt?: string | null;
  usersCount?: number;
  /** @nullable */
  permissions?: PermissionDto[] | null;
}
