/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */
import type { IntPtr } from './intPtr';

export interface RuntimeMethodHandle {
  value?: IntPtr;
}
