/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */

export type SenderTypeEnum = typeof SenderTypeEnum[keyof typeof SenderTypeEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SenderTypeEnum = {
  NUMBER_0: 0,
  NUMBER_1: 1,
} as const;
