/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */

export interface SignUpWithPhoneNumberRequest {
  /** @nullable */
  phoneNumber?: string | null;
  /** @nullable */
  referencedBy?: string | null;
  documentsAccepted?: boolean;
  /** @nullable */
  fcmToken?: string | null;
}
