/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */
import type { PlatformTypeEnum } from './platformTypeEnum';

export interface SmsSettingsDto {
  id?: string;
  createdAt?: string;
  platformType?: PlatformTypeEnum;
  /** @nullable */
  providerName?: string | null;
  /** @nullable */
  apiKey?: string | null;
  /** @nullable */
  apiSecret?: string | null;
  /** @nullable */
  senderNumber?: string | null;
}
