/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */

export interface StringListApiResponse {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  data?: string[] | null;
  /** @nullable */
  errors?: string[] | null;
  /** @nullable */
  errorCode?: string | null;
  statusCode?: number;
}
