/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */
import type { StructLayoutAttributeTypeId } from './structLayoutAttributeTypeId';
import type { LayoutKind } from './layoutKind';

export interface StructLayoutAttribute {
  /** @nullable */
  readonly typeId?: StructLayoutAttributeTypeId;
  value?: LayoutKind;
}
