/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */

export type TagTypeEnum = typeof TagTypeEnum[keyof typeof TagTypeEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TagTypeEnum = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
} as const;
