/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */

export type TaskCreationOptions = typeof TaskCreationOptions[keyof typeof TaskCreationOptions];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TaskCreationOptions = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_4: 4,
  NUMBER_8: 8,
  NUMBER_16: 16,
  NUMBER_64: 64,
} as const;
