/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */
import type { TelegramSettingsDto } from './telegramSettingsDto';

export interface TelegramSettingsDtoApiResponse {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: TelegramSettingsDto;
  /** @nullable */
  errors?: string[] | null;
  /** @nullable */
  errorCode?: string | null;
  statusCode?: number;
}
