/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */
import type { PlatformTypeEnum } from './platformTypeEnum';

export interface TelegramSettingsDto {
  id?: string;
  createdAt?: string;
  platformType?: PlatformTypeEnum;
  /** @nullable */
  botToken?: string | null;
}
