/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */
import type { PlatformTypeEnum } from './platformTypeEnum';
import type { EventTypeEnum } from './eventTypeEnum';
import type { TelegramMessageEventParameters } from './telegramMessageEventParameters';

export interface TelegramMessageEvent {
  platformType?: PlatformTypeEnum;
  eventType?: EventTypeEnum;
  /** @nullable */
  to?: string | null;
  /** @nullable */
  body?: string | null;
  /** @nullable */
  subject?: string | null;
  /** @nullable */
  templateName?: string | null;
  useTemplate?: boolean;
  isHtml?: boolean;
  /** @nullable */
  parameters?: TelegramMessageEventParameters;
  disableNotification?: boolean;
  /** @nullable */
  replyToMessageId?: number | null;
}
