/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */
import type { TwoFactorMethodEnum } from './twoFactorMethodEnum';

export interface ToggleTotpRequest {
  /** @nullable */
  userId?: string | null;
  /** @nullable */
  totp: string | null;
  enabled: boolean;
  method: TwoFactorMethodEnum;
}
