/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */

export interface UpdatePushNotificationSettingsRequest {
  /** @nullable */
  fcmServerKey?: string | null;
  /** @nullable */
  deviceTokens?: string[] | null;
  /** @nullable */
  topic?: string | null;
  /** @nullable */
  id?: string | null;
}
