/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */
import type { TagTypeEnum } from './tagTypeEnum';

export interface UpdateTagRequest {
  tagType?: TagTypeEnum;
  /** @nullable */
  id?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  metaData?: string | null;
}
