/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */

export interface UpdateAuthorRequest {
  /** @nullable */
  id?: string | null;
  /** @nullable */
  fullName?: string | null;
  /** @nullable */
  imageUrl?: string | null;
  /** @nullable */
  title?: string | null;
}
