/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */
import type { UserWithRoles } from './userWithRoles';

export interface UserWithRolesListPaginationResponse {
  totalCount?: number;
  /** @nullable */
  items?: UserWithRoles[] | null;
}
