/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */

export interface UserProfileInfoDto {
  id?: string;
  emailConfirmed?: boolean;
  phoneNumberConfirmed?: boolean;
  /** @nullable */
  email: string | null;
  /** @nullable */
  phoneNumber?: string | null;
  /** @nullable */
  firstName?: string | null;
  /** @nullable */
  lastName?: string | null;
  /** @nullable */
  avatar?: string | null;
  createdAt?: string;
}
