/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */
import type { UserProfileInfoDto } from './userProfileInfoDto';

export interface UserProfileInfoDtoApiResponse {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: UserProfileInfoDto;
  /** @nullable */
  errors?: string[] | null;
  /** @nullable */
  errorCode?: string | null;
  statusCode?: number;
}
