/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */
import type { AggregateException } from './aggregateException';
import type { TaskStatus } from './taskStatus';
import type { TaskCreationOptions } from './taskCreationOptions';
import type { UserWithRolesListPaginationResponseApiResponseTaskAsyncState } from './userWithRolesListPaginationResponseApiResponseTaskAsyncState';
import type { UserWithRolesListPaginationResponseApiResponse } from './userWithRolesListPaginationResponseApiResponse';

export interface UserWithRolesListPaginationResponseApiResponseTask {
  readonly id?: number;
  exception?: AggregateException;
  status?: TaskStatus;
  readonly isCanceled?: boolean;
  readonly isCompleted?: boolean;
  readonly isCompletedSuccessfully?: boolean;
  creationOptions?: TaskCreationOptions;
  /** @nullable */
  readonly asyncState?: UserWithRolesListPaginationResponseApiResponseTaskAsyncState;
  readonly isFaulted?: boolean;
  result?: UserWithRolesListPaginationResponseApiResponse;
}
