/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */

export interface UserWithRoles {
  userId?: string;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  roles?: string[] | null;
}
