/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */
import type { UserProfileInfoDtoListPaginationResponse } from './userProfileInfoDtoListPaginationResponse';

export interface UserProfileInfoDtoListPaginationResponseApiResponse {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: UserProfileInfoDtoListPaginationResponse;
  /** @nullable */
  errors?: string[] | null;
  /** @nullable */
  errorCode?: string | null;
  statusCode?: number;
}
