/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BackendForAdmin
 * OpenAPI spec version: v1
 */
import type { UserWithRolesListPaginationResponse } from './userWithRolesListPaginationResponse';

export interface UserWithRolesListPaginationResponseApiResponse {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: UserWithRolesListPaginationResponse;
  /** @nullable */
  errors?: string[] | null;
  /** @nullable */
  errorCode?: string | null;
  statusCode?: number;
}
